'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TBK_FA_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addActualNumpad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addActualNumpad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addActualNumpad1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addActualNumpad1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addActualNumpad2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addActualNumpad2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addActualNumpad3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addActualNumpad3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addActualNumpad4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addActualNumpad4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addActualNumpadspa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addActualNumpadspa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addActualNumpadspaissue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addActualNumpadspaissue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addLossNumpad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addLossNumpad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addSpeNumpad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addSpeNumpad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addSpeNumpad1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addSpeNumpad1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property autoLoss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("autoLoss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BLOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BLOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property breaktime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breaktime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property breaktime1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breaktime1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property breaktime2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breaktime2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property breaktime3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breaktime3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnCloselot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCloselot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDefect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDefect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnInc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnInc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnokkk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnokkk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnSetting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSetting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnStart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnStart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnstartbreaktime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnstartbreaktime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnstartbreaktime1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnstartbreaktime1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnstartbreaktime2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnstartbreaktime2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cf250687395151_5db728c7879d3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cf250687395151.5db728c7879d3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closeLotsummary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeLotsummary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closeLotsummary1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeLotsummary1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property configLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property configLine1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configLine1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property configLine2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configLine2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property decreaseActualNumpad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("decreaseActualNumpad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailadjustNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailadjustNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailadjustNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailadjustNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailselectadjustNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailselectadjustNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailselectadjustNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailselectadjustNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadadjust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadadjust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadregister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadregister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadregister1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadregister1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadregister2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadregister2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminregister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminregister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminregister1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminregister1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminsearchNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminsearchNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminsearchNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminsearchNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselectcodeNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselectcodeNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselectcodeNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselectcodeNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselecttypeNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselecttypeNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselecttypeNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselecttypeNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselecttypeNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselecttypeNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAlertsure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAlertsure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAlertsure1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAlertsure1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAlertupdate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAlertupdate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectDetailnc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectDetailnc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectDetailnc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectDetailnc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectDetailnc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectDetailnc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectNumpadadjust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectNumpadadjust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectNumpadregister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectNumpadregister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectRegister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectRegister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectRegister1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectRegister1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectRegister2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectRegister2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectSelectcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectSelectcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectSelecttype() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectSelecttype", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dwdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dwdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dwdd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dwdd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eadb74787dda41cc6333341e55293432() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eadb74787dda41cc6333341e55293432", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exitProgram() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitProgram", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_qty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_qty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_qty2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_qty2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loginAdmin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginAdmin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loginAdmin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginAdmin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoTBKK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoTBKK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenu2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenu2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenu3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenu3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenu4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenu4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property man() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("man", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manageEmp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manageEmp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manageEmp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manageEmp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manageEmp2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manageEmp2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manageEmp3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manageEmp3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manageEmp4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manageEmp4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manualLossAfter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manualLossAfter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manualLossAfter1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manualLossAfter1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manualLossBefor1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manualLossBefor1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manualLossBefore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manualLossBefore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menuLogin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuLogin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionListDetail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionListDetail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionListDetail2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionListDetail2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStart1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStart1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStart2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStart2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStart3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStart3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStart4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStart4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStart5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStart5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStarting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStarting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStarting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStarting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStarting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStarting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStarting3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStarting3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStarting4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStarting4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStarting5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStarting5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStartingtarget() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStartingtarget", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStarttarget() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStarttarget", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStopped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStopped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStopped1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStopped1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStopped2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStopped2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStopped3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStopped3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStopped4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStopped4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStopped5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStopped5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property productionStoppedtarget() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productionStoppedtarget", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reprintTag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reprintTag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reprintTag1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reprintTag1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanAdminAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanAdminAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanAdminAccount1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanAdminAccount1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanEmpCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanEmpCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanMaterial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanMaterial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectLoss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectLoss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectLoss1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectLoss1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectLoss2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectLoss2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectLoss3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectLoss3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectNormalRework() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectNormalRework", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectShift() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectShift", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property setupMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setupMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property setupMenu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setupMenu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sweetAlertSuccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sweetAlertSuccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sweetAlertWarningUnseccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sweetAlertWarningUnseccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
